import { Post, User, Todo } from "./types";

export const CURRENT_USER: User = {
  id: "u1",
  name: "Valentina Cruz",
  username: "vcruz",
  avatar: "VC",
  role: "student",
  university: "UNAM",
  followers: 312,
  following: 89,
  bio: "CS @ UNAM · Interested in ML, distributed systems & academic equity.",
};

export const MOCK_USERS: User[] = [
  CURRENT_USER,
  {
    id: "u2",
    name: "Diego Ramírez",
    username: "dramirez",
    avatar: "DR",
    role: "creator",
    university: "IPN",
    followers: 1402,
    following: 210,
    bio: "Math & Physics educator. Creator of premium problem sets.",
  },
  {
    id: "u3",
    name: "Sofia Herrera",
    username: "sherrera",
    avatar: "SH",
    role: "creator",
    university: "TEC",
    followers: 890,
    following: 134,
    bio: "Data Science instructor. Building structured learning paths.",
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    author: MOCK_USERS[1],
    type: "post",
    body:
      "Just wrapped up a full derivation of the Fourier Transform from first principles. Thread below — DM me for the LaTeX source. This is the approach I use with my students and it cuts confusion by ~60%.",
    tags: ["math", "calculus", "fourier"],
    likes: 248,
    comments: 34,
    saves: 91,
    createdAt: "2h ago",
    isPremium: false,
    subject: "Mathematics",
    liked: false,
    saved: false,
  },
  {
    id: "p2",
    author: MOCK_USERS[2],
    type: "course",
    title: "Intro to Data Science with Python — 2025 Edition",
    body:
      "12 modules, 40+ notebooks, real datasets. Covers pandas, sklearn, visualization and a final capstone project. Fully updated for Python 3.12.",
    tags: ["python", "datascience", "ML"],
    likes: 512,
    comments: 67,
    saves: 203,
    createdAt: "5h ago",
    isPremium: true,
    price: 149,
    subject: "Data Science",
    liked: false,
    saved: true,
  },
  {
    id: "p3",
    author: MOCK_USERS[0],
    type: "resource",
    title: "Algorithms Cheat Sheet — Big O Reference",
    body:
      "One-page reference for Big O complexities across sorting, searching, graph, and DP algorithms. PDF available. Great for technical interview prep.",
    tags: ["algorithms", "cs", "interview"],
    likes: 876,
    comments: 112,
    saves: 430,
    createdAt: "1d ago",
    isPremium: false,
    subject: "Computer Science",
    liked: true,
    saved: false,
  },
  {
    id: "p4",
    author: MOCK_USERS[1],
    type: "book",
    title: "Linear Algebra: Intuition Before Formalism",
    body:
      "A 200-page ebook that builds visual intuition for vector spaces, eigenvalues, and SVD before introducing notation. Ideal for ML practitioners.",
    tags: ["linearalgebra", "ebook", "ML"],
    likes: 341,
    comments: 45,
    saves: 188,
    createdAt: "2d ago",
    isPremium: true,
    price: 89,
    subject: "Mathematics",
    liked: false,
    saved: false,
  },
  {
    id: "p5",
    author: MOCK_USERS[2],
    type: "post",
    body:
      "Hot take: most universities still teach statistics from 1970s textbooks. Here are 5 modern resources that actually teach you how to think probabilistically in 2025.",
    tags: ["statistics", "education", "resources"],
    likes: 193,
    comments: 58,
    saves: 77,
    createdAt: "3d ago",
    isPremium: false,
    subject: "Statistics",
    liked: false,
    saved: false,
  },
];

export const MOCK_TODOS: Todo[] = [
  {
    id: "t1",
    text: "Finish Chapter 5 exercises — Discrete Math",
    done: false,
    label: "assignment",
    dueDate: "Today",
    priority: "high",
  },
  {
    id: "t2",
    text: "Review lecture notes for Algorithms midterm",
    done: false,
    label: "exam",
    dueDate: "Jun 6",
    priority: "high",
  },
  {
    id: "t3",
    text: "Read Ramírez's Fourier Transform thread",
    done: true,
    label: "study",
    dueDate: undefined,
    priority: "low",
  },
  {
    id: "t4",
    text: "Submit final project report draft",
    done: false,
    label: "project",
    dueDate: "Jun 10",
    priority: "medium",
  },
  {
    id: "t5",
    text: "Set up Python environment for DS course",
    done: true,
    label: "study",
    dueDate: undefined,
    priority: "medium",
  },
  {
    id: "t6",
    text: "Buy Linear Algebra ebook",
    done: false,
    label: "personal",
    dueDate: undefined,
    priority: "low",
  },
];
